#!/bin/bash

#################################################################################
########   export varible to used in makefile   #################################
export wrkdir=$(shell pwd)
export kerMake=$(wrkdir)/kernelSRC
export buildFolder=$(wrkdir)/kernelBuildFiles
export output=$(wrkdir)/output
export myConfig=$(output)/myKernelConfig

##make options
mkopt=--no-print-directory

#################################################################################
.PHONY: all
all:
	@echo "nothing for all ; use help"

#################################################################################
help:
	@make $(mkopt) -C $(kerMake) help
#################################################################################
vars:
	@echo "wrkdir = $(wrkdir)"
	@make $(mkopt) -C $(kerMake) vars
#################################################################################
deps:
	@make $(mkopt) -C $(kerMake) deps
#################################################################################
update:
	@make $(mkopt) -C $(kerMake) update
#################################################################################
menuconfig:
	@make $(mkopt) -C $(kerMake) menuconfig
#################################################################################
defconfig_x86:
	@make $(mkopt) -C $(kerMake) defconfig_x86
#################################################################################
src:
	@make $(mkopt) -C $(kerMake) src
#################################################################################
clean:
	@make $(mkopt) -C $(kerMake) clean
#################################################################################
cleanall:
	@make $(mkopt) -C $(kerMake) cleanall
#################################################################################
build:
	@make $(mkopt) -C $(kerMake) build
#################################################################################
rebuild:
	@make $(mkopt) -C $(kerMake) rebuild
#################################################################################
modules:
	@make $(mkopt) -C $(kerMake) modules
#################################################################################
outOfTree:
	@make $(mkopt) -C $(kerMake) outOfTree modFold=$(wrkdir)/${folder} module=${module}
#################################################################################
cpout:
	@make $(mkopt) -C $(kerMake) cpout
#################################################################################


